import { existsSync } from "fs";
import { writeFile } from "fs/promises";

// const imgurIds = [
//   "01ljhph",
//   "04DFta6",
//   "07Avtki",
//   "0acgduU",
//   "0Ku2KhY",
//   "0kVLzFV",
//   "0LtxgSj",
//   "0maOvqW",
//   "0MMxaD1",
//   "0oFj6Xy",
//   "0OlTim6",
//   "0r3hSq3",
//   "0rUoHHm",
//   "11MNivm",
//   "17UN32H",
//   "194PCuy",
//   "1EqhBSF",
//   "1IpjwvJ",
//   "1J2tNiq",
//   "1MYRsSv",
//   "1QSxMku",
//   "1sOdoQt",
//   "1xmRy03",
//   "1xxmI2a",
//   "1YwlAFa",
//   "24kPD64",
//   "26X166P",
//   "2ahJUK5",
//   "2e0FYM9",
//   "2mjwnIJ",
//   "2qraP1g",
//   "2tZkQvQ",
//   "2uzaxiD",
//   "2x4a5ya",
//   "2z8lGsd",
//   "2ZKrXjU",
//   "36WDLb4",
//   "3bSrP5e",
//   "3bUMPma",
//   "3CnX3MX",
//   "3gGQhnZ",
//   "3lJtPC0",
//   "3O0W5v7",
//   "3p6cIFs",
//   "3pGp1yy",
//   "3PLB5Ht",
//   "3SkGjEZ",
//   "3VlXA9h",
//   "4CYyaWe",
//   "4f1NMTF",
//   "4Foxury",
//   "4Hf72Le",
//   "4io6n3z",
//   "4kO0WuI",
//   "4kxnxUJ",
//   "4Ls0NO5",
//   "4nYzyJs",
//   "4yvofFE",
//   "50JYqsw",
//   "53J1sT3",
//   "54uaoeV",
//   "5dyZ3o3",
//   "5G6Kn1C",
//   "5j1I4vR",
//   "5O0ghAQ",
//   "5o8Z1Tt",
//   "5tyrYe3",
//   "5xlpQiv",
//   "61L3hpE",
//   "65ZXbKR",
//   "6BTUx6L",
//   "6CL4RwZ",
//   "6my9fUx",
//   "6yGCKM6",
//   "6ZQ7N8v",
//   "7aG8nO4",
//   "7alAobq",
//   "7h14bR3",
//   "7IJRMcR",
//   "7JHcAPj",
//   "7pB0PVg",
//   "7TOMlsV",
//   "7vCdbzV",
//   "7wxuthx",
//   "7xrT3MG",
//   "80KyNTS",
//   "8DAWWY7",
//   "8GPEIL6",
//   "8IHQ0QU",
//   "8MpQv5X",
//   "8nYOC2B",
//   "8rP0GLu",
//   "8yhr9xT",
//   "8zRjiJI",
//   "8zZ65t1",
//   "95CVxp2",
//   "9AMlrZH",
//   "9aP8yPQ",
//   "9I3vrGI",
//   "9iSgeKj",
//   "9m1VjmE",
//   "9nGy7na",
//   "9wXGJhP",
//   "9ZbtRUm",
//   "a0K7GCy",
//   "A0Yvsf7",
//   "A4Mp9aR",
//   "a5fB884",
//   "A7bXd33",
//   "a8pB9v3",
//   "afBKtL5",
//   "Agdszmb",
//   "AHeDDQl",
//   "ahmjGoZ",
//   "ahP4bvR",
//   "AKF9BBR",
//   "aKOmQde",
//   "anKPcEq",
//   "Ao6E8rK",
//   "aRXZ766",
//   "AudUzNX",
//   "AVfRUfh",
//   "awvYf9L",
//   "AyhiTzZ",
//   "aZEmAZv",
//   "aZw6sBz",
//   "B0XZCao",
//   "bamGsWx",
//   "baxYTZF",
//   "Bdi551u",
//   "bFaeRsp",
//   "bn1Ht27",
//   "boGngyI",
//   "bPLNbqw",
//   "bqyET8v",
//   "BTdKtF9",
//   "Btoezr3",
//   "BxngAcm",
//   "bYjgkIE",
//   "bzKO9XP",
//   "c7UBUMx",
//   "C93uXmV",
//   "CaElmEG",
//   "CcYZkl7",
//   "cDRWBta",
//   "CGLgdvR",
//   "cH2ze97",
//   "ChRnxO1",
//   "cJ85mdc",
//   "cjmqyCu",
//   "cJPMtDE",
//   "CmSHQLW",
//   "cOpDfqs",
//   "CVgcCoB",
//   "cw5kVu5",
//   "cXNlmrk",
//   "d3P7M6v",
//   "D4qEjgU",
//   "D7ynj0a",
//   "daCZEQw",
//   "dAoTn5q",
//   "DBjamQJ",
//   "DC15nWf",
//   "deEx4IK",
//   "DEZfUNs",
//   "dgBN1iZ",
//   "dH0Mkwa",
//   "DhTB9Jt",
//   "DIpFafb",
//   "Dj2nqfV",
//   "dl4DXKm",
//   "dseObqD",
//   "dSlOLo5",
//   "DtMyPU4",
//   "DVVBdF3",
//   "DWfeA1u",
//   "DWHFck2",
//   "DyEz1ZZ",
//   "DyUJ6JV",
//   "DZSUgJ2",
//   "e1CwOfg",
//   "e3vJE0l",
//   "eAmTsiZ",
//   "EAo8PLs",
//   "eBIG5R0",
//   "ecLsIqR",
//   "efwTcve",
//   "EfXSNLG",
//   "ej7igQO",
//   "EjNJbli",
//   "EPf2onF",
//   "ePZHDDy",
//   "ErMFOKL",
//   "Et1zVwQ",
//   "EVAGmc1",
//   "eWWlZjD",
//   "ExBojeU",
//   "EZfr3yQ",
//   "EzTai7f",
//   "EZxTRHT",
//   "f4IOwWI",
//   "fcWXd9l",
//   "fflQ29l",
//   "fhdideH",
//   "fHxHuoI",
//   "Fkik1Do",
//   "fKj1V7K",
//   "fMmY6OL",
//   "fnqNrNl",
//   "fO8GSLk",
//   "FpRkrUQ",
//   "frgLUoK",
//   "FRNvEr0",
//   "FSuA9x5",
//   "FUcgUAu",
//   "fugZY8I",
//   "fv6uFPp",
//   "Fvj1nbg",
//   "fWqsV49",
//   "Fx38KtK",
//   "fYCHxiX",
//   "fz2cuqp",
//   "FZ5uncT",
//   "fzahOBP",
//   "fzGwzVQ",
//   "g8GJGfI",
//   "geikbAO",
//   "gGqKGG5",
//   "gHC4cA6",
//   "gMYlkZh",
//   "goaFtTe",
//   "gOWXNq4",
//   "gpIgrkl",
//   "gpu4Fyj",
//   "gQ5IrM1",
//   "gQPaCov",
//   "grnjkmC",
//   "gsANnWx",
//   "gSIIyeB",
//   "gU5VXx6",
//   "gubVnHJ",
//   "gvG7DdM",
//   "gxQ3QA1",
//   "gXRUp18",
//   "GYO1iQ2",
//   "h5DhQwY",
//   "h5sQidd",
//   "HAcOU3v",
//   "HdNhyok",
//   "HhlxgUk",
//   "hHsbc7S",
//   "hJaM5kV",
//   "HjCvwIN",
//   "HkRdXLb",
//   "hlW6W6r",
//   "HmgnFRA",
//   "HPJwkPt",
//   "HsjoYhB",
//   "HSkjbnz",
//   "HToMlpe",
//   "HUn9bPx",
//   "HWC7uTb",
//   "HZRVd8n",
//   "HZUfeFE",
//   "HZUqd1D",
//   "I0XMeOz",
//   "i1QUncM",
//   "i22hSwj",
//   "i5og0dU",
//   "IdEATD3",
//   "iE7FGly",
//   "Ih8S99c",
//   "IjN1dT6",
//   "iLaweEn",
//   "ImM8rvg",
//   "iMoj5qA",
//   "IoB18cV",
//   "ISnaLBD",
//   "IToOtId",
//   "ivyomjK",
//   "IxWMIhD",
//   "j50QIuM",
//   "j57FbGf",
//   "j83kSI7",
//   "jaoyt0n",
//   "jaxstnK",
//   "jEyxnbV",
//   "jgC53ZX",
//   "JMmT7qh",
//   "JNOTgwp",
//   "JSukWUk",
//   "jT7bq4S",
//   "jtQZyF6",
//   "JtWr9pW",
//   "JWSIr2c",
//   "jz8J5P8",
//   "K2bqxvt",
//   "k3L7Zmo",
//   "K3pxorP",
//   "k4WQRvk",
//   "k8ivc3f",
//   "kAs0zg2",
//   "kBcTyaj",
//   "kD1Y1va",
//   "KDsIbXY",
//   "KDue2cs",
//   "Kf4wYDY",
//   "KFb1o3t",
//   "kfim2Sr",
//   "kfN64ue",
//   "KHH32nW",
//   "KHSXsI9",
//   "KkkHdSW",
//   "KnSlyi7",
//   "knt3sVA",
//   "KOr08u6",
//   "kp3sQae",
//   "kq1mQMI",
//   "ks1Zyfa",
//   "ksais63",
//   "KV9JPvp",
//   "kvh0ild",
//   "KxmFRfz",
//   "kxsWOKq",
//   "KyoG8de",
//   "lcOKOdu",
//   "lCpgonU",
//   "Ldq6QRR",
//   "LfGW6sl",
//   "LFxSKRT",
//   "lGVe4iW",
//   "litybtv",
//   "LIVH6nv",
//   "Ljhf0X6",
//   "LJhiN0m",
//   "LK375TS",
//   "LLrlxHV",
//   "lmPr0ob",
//   "Lol0IHa",
//   "LP60W0A",
//   "lQHpR5x",
//   "Lrk5Erw",
//   "LSarK9j",
//   "LUeI9b8",
//   "Luk48jY",
//   "lWi60zs",
//   "LXLxwnq",
//   "lxp63qH",
//   "M060Hxu",
//   "M3b6wLw",
//   "m7CzZ2I",
//   "MaE1ICP",
//   "mBIWm9E",
//   "MeQ1im8",
//   "mGjKDOT",
//   "MHJo2My",
//   "MinNQCQ",
//   "mJ5eAVi",
//   "Mlrx3f6",
//   "MMBYhc6",
//   "mOL28YC",
//   "mQdOrFt",
//   "MqZ9p3Z",
//   "MsRNmcq",
//   "mt3cuML",
//   "Mtys2r2",
//   "MVg1gAS",
//   "mXnSeko",
//   "Mz4SiA4",
//   "nbgX3uo",
//   "Ndzfn2W",
//   "nExINgG",
//   "NHmCcdx",
//   "nhn8ckv",
//   "nOY5hkR",
//   "Nrq5n0w",
//   "NRXEj4M",
//   "nsAjW5T",
//   "NTPLsYf",
//   "nuRnffr",
//   "nxdq3c7",
//   "nZ3mTGC",
//   "O4MnmPw",
//   "O4n5yro",
//   "o54k9Zt",
//   "o86uzUJ",
//   "oaZQjSC",
//   "oBLqTQK",
//   "oChHkRw",
//   "OeFzvsb",
//   "ohDvIaW",
//   "ojRlkRk",
//   "oKGcS7g",
//   "olWF73B",
//   "ONciAa2",
//   "OPSRQJg",
//   "oRzHNX6",
//   "os6nuxz",
//   "Ouv0ttR",
//   "oZR1cSr",
//   "p1h802V",
//   "P5HgRug",
//   "P7OwrnC",
//   "p8EKTeo",
//   "pa3AFfa",
//   "pBlXfo7",
//   "PCbyhNc",
//   "pDBJqU7",
//   "PdFBJC6",
//   "pdHUeXO",
//   "PfIYGRN",
//   "PGERTCZ",
//   "pILtgDp",
//   "pjWr2gG",
//   "PkQGw2N",
//   "PlBhEe5",
//   "PPEmzME",
//   "pxNB1D6",
//   "pYFvdE8",
//   "Q9BTECm",
//   "qczcNjH",
//   "QEVkk3s",
//   "qFj0rEs",
//   "Qg0ikxA",
//   "qhxfOai",
//   "qkRO8b6",
//   "QKrU5un",
//   "QMUA2AB",
//   "QmyMrN8",
//   "QpPWrXU",
//   "QSpwkNV",
//   "QSr7f1s",
//   "QtWv6Z8",
//   "R2iVZhn",
//   "r3OPum2",
//   "R4YfH3R",
//   "R9MoCZ3",
//   "rA2hlhR",
//   "raB2eBi",
//   "rb2m56H",
//   "RCJ5i9i",
//   "rdqYNG6",
//   "rdRBsqF",
//   "rEmsAda",
//   "rex1fYt",
//   "rGQkxnr",
//   "RHiNHaU",
//   "RIPHm7J",
//   "RiqwV1Q",
//   "rL2Xcm3",
//   "RmuJT2x",
//   "rp8lLwQ",
//   "Rr3OTDE",
//   "RSHwFTb",
//   "ruwvVbW",
//   "RvR9XW2",
//   "RxRM1lW",
//   "S1lbKG4",
//   "S6khzhg",
//   "S6PcMxi",
//   "s7ZitgL",
//   "Sa9oicX",
//   "sE69gvC",
//   "SjgJWZn",
//   "SKsNnij",
//   "sKSUWMC",
//   "SlgvXuE",
//   "sMUO99b",
//   "SNdTxzm",
//   "sP7vss8",
//   "SqDk1tO",
//   "SR0Gx51",
//   "sr11mKs",
//   "sV9sLNP",
//   "sYNAnZT",
//   "T0MwTyI",
//   "TBcVHKk",
//   "TgiJXEu",
//   "TJ7KhMn",
//   "TJFM6AM",
//   "TK1Mo66",
//   "Tk4GIeV",
//   "TMCIxrg",
//   "TnjrrRD",
//   "To5U8Vj",
//   "ttGX4D8",
//   "TTtKvaG",
//   "tVJy7dV",
//   "TwSkOY7",
//   "tyC6fyz",
//   "tZ36EV8",
//   "U0uT02l",
//   "U8lqQgW",
//   "U901NNi",
//   "uc9KQOF",
//   "udk0QyR",
//   "uEbGB1c",
//   "UhEGkzn",
//   "UHvLlvr",
//   "uIQX4YW",
//   "UJ8Mjhl",
//   "unCumdN",
//   "uNrHVci",
//   "UtGigbH",
//   "uUwZMGR",
//   "UVJGjzR",
//   "UvKEmf7",
//   "UWUwe7m",
//   "uYUS46G",
//   "uyXCObF",
//   "V6sFYjP",
//   "v9hDvcg",
//   "V9kHfCS",
//   "v9lYGlE",
//   "vBDcpaL",
//   "VdnotBm",
//   "vIPttW6",
//   "VJu2XCJ",
//   "VLQ5fCV",
//   "vp7BTSt",
//   "vq4LDfS",
//   "vR07MdW",
//   "VtUPc6D",
//   "VUIQWmk",
//   "VVqsDXH",
//   "vwYbil8",
//   "VX8u6vM",
//   "Vy4H3Ms",
//   "vyClfzz",
//   "vzG1QZj",
//   "W3BFSJS",
//   "w4jhZna",
//   "w4rzsCX",
//   "w5Vql3g",
//   "waybbXq",
//   "WD5ZzBg",
//   "wdoWPaQ",
//   "We9Vi6a",
//   "wfLLgt5",
//   "WjOZ4Sr",
//   "WlFEqzG",
//   "Wmrtrow",
//   "WOB1w7S",
//   "WPtWVOj",
//   "WqkmrQf",
//   "wUiUkdH",
//   "WVNHbnu",
//   "wXrrGJz",
//   "wzHkifX",
//   "x41cioC",
//   "X9L0XcO",
//   "xAJ6J0p",
//   "XaLZdW2",
//   "xbkqiP4",
//   "XdFK3uA",
//   "XehK5Z7",
//   "XFmD7Is",
//   "XFR7m2E",
//   "xHmJ8Nq",
//   "XJIxk5n",
//   "xL4I3hL",
//   "xMlnCuQ",
//   "XNo0xSk",
//   "XpEm2VJ",
//   "xqjlPZ3",
//   "xS6Eu4p",
//   "XSqtDMi",
//   "xSwN6sy",
//   "xuHj8H5",
//   "Xvb7A1T",
//   "XwZndzf",
//   "Y2lxdRA",
//   "y7duaFV",
//   "yC4nscY",
//   "YDA6HgR",
//   "YfubuM4",
//   "yiwSsMK",
//   "yjWenJM",
//   "YkadC5L",
//   "YL69ozC",
//   "YnxsDwQ",
//   "yONidkC",
//   "yOOUeCI",
//   "YPEkYqr",
//   "YpfMce3",
//   "yQlsKK6",
//   "YRDLKbV",
//   "YtBD7k4",
//   "yZh2fmo",
//   "YzwC4U0",
//   "Z06Nhkg",
//   "Z4mQih3",
//   "z89tKk3",
//   "z8zEMZ5",
//   "zIqzECD",
//   "ZIvDXIj",
//   "ZJVwXJo",
//   "zKNGfkA",
//   "ZKyQbHm",
//   "zLaluPn",
//   "zLC4R96",
//   "zMLbszv",
//   "ZN5ZZFs",
//   "zpv3plJ",
//   "zQ0PvO5",
//   "zQLNbVo",
//   "zTKSD90",
//   "ZVBDy8T",
//   "zwi9QgG",
//   "ZyC9DNj",
// ];

const imgurIds = [
  "04DFta6.png",
  "07Avtki.png",
  "0acgduU.png",
  "0Ku2KhY.png",
  "0maOvqW.png",
  "0oFj6Xy.gif",
  "0rUoHHm.png",
  "17UN32H.png",
  "194PCuy.jpg",
  "1IpjwvJ.gif",
  "1MYRsSv.png",
  "1pdD2p2.png",
  "1QSxMku.png",
  "1sOdoQt.png",
  "1xmRy03.png",
  "1xxmI2a.png",
  "26X166P.jpg",
  "2AqwaSA.png",
  "2mjwnIJ.jpg",
  "2uzaxiD.png",
  "2x4a5ya.jpg",
  "2z8lGsd.png",
  "2ZKrXjU.png",
  "36WDLb4.png",
  "3bSrP5e.png",
  "3bUMPma.png",
  "3CnX3MX.jpg",
  "3gGQhnZ.png",
  "3lJtPC0.jpg",
  "3O0W5v7.png",
  "3p6cIFs.png",
  "3pGp1yy.png",
  "3SkGjEZ.jpg",
  "3VlXA9h.png",
  "4f1NMTF.png",
  "4Foxury.png",
  "4io6n3z.png",
  "4kxnxUJ.png",
  "53J1sT3.png",
  "54uaoeV.png",
  "5dyZ3o3.jpg",
  "5j1I4vR.png",
  "5tyrYe3.jpg",
  "5xlpQiv.png",
  "65ZXbKR.png",
  "6BTUx6L.png",
  "6CL4RwZ.jpg",
  "6my9fUx.gif",
  "7aG8nO4.png",
  "7alAobq.png",
  "7h14bR3.jpg",
  "7JHcAPj.png",
  "7pB0PVg.png",
  "7TOMlsV.png",
  "7xrT3MG.png",
  "80KyNTS.jpg",
  "886 results",
  "8DAWWY7.jpg",
  "8FVEf2V.png",
  "8GPEIL6.png",
  "8nYOC2B.jpg",
  "8yhr9xT.png",
  "8zRjiJI.png",
  "8zZ65t1.png",
  "9aP8yPQ.jpg",
  "9wXGJhP.gif",
  "9ZbtRUm.png",
  "a0K7GCy.jpg",
  "A0Yvsf7.jpg",
  "A4Mp9aR.png",
  "a5fB884.gif",
  "A7bXd33.png",
  "Agdszmb.png",
  "AHeDDQl.png",
  "ahP4bvR.jpg",
  "ahP4bvR.png",
  "aKOmQde.jpg",
  "anKPcEq.jpg",
  "anKPcEq.png",
  "Ao6E8rK.png",
  "AVfRUfh.png",
  "awvYf9L.gif",
  "AyhiTzZ.png",
  "aZw6sBz.jpg",
  "bamGsWx.jpg",
  "bamGsWx.png",
  "bFaeRsp.png",
  "bn1Ht27.png",
  "boGngyI.png",
  "bPLNbqw.png",
  "Brr95O0.png",
  "BTdKtF9.png",
  "bYjgkIE.png",
  "bzKO9XP.png",
  "c7UBUMx.png",
  "cDRWBta.jpg",
  "CGLgdvR.png",
  "cH2ze97.png",
  "CmSHQLW.png",
  "cOuoA0N.png",
  "cw5kVu5.png",
  "D4qEjgU.gif",
  "dAoTn5q.png",
  "DBjamQJ.jpg",
  "DC15nWf.png",
  "deEx4IK.png",
  "dgBN1iZ.png",
  "DhTB9Jt.jpg",
  "DIpFafb.jpg",
  "Dj2nqfV.png",
  "dl4DXKm.png",
  "dseObqD.png",
  "dSlOLo5.png",
  "DtMyPU4.png",
  "DWfeA1u.png",
  "DWHFck2.gif",
  "DyEz1ZZ.png",
  "DyUJ6JV.png",
  "e1CwOfg.png",
  "e2azNfa.png",
  "e3vJE0l.png",
  "eAmTsiZ.jpg",
  "EAo8PLs.jpg",
  "efwTcve.png",
  "EfXSNLG.png",
  "ej7igQO.png",
  "EPf2onF.mp4",
  "EPf2onF.png",
  "ePZHDDy.png",
  "ErMFOKL.mp4",
  "ErMFOKL.png",
  "Et1zVwQ.png",
  "EVAGmc1.png",
  "eWWlZjD.jpg",
  "eX0BT7Y.png",
  "fcWXd9l.jpg",
  "fhdideH.png",
  "fHxHuoI.png",
  "fKj1V7K.png",
  "fMmY6OL.png",
  "fnqNrNl.png",
  "fO8GSLk.png",
  "FRNvEr0.png",
  "FSuA9x5.png",
  "FUcgUAu.png",
  "fugZY8I.png",
  "fv6uFPp.png",
  "Fvj1nbg.jpg",
  "fWqsV49.jpg",
  "Fx38KtK.png",
  "fYCHxiX.png",
  "fz2cuqp.jpg",
  "FZ5uncT.jpg",
  "fzahOBP.png",
  "fzGwzVQ.jpg",
  "fzGwzVQ.mp4",
  "g8GJGfI.mp4",
  "g8GJGfI.png",
  "geikbAO.png",
  "gGqKGG5.png",
  "gHC4cA6.gif",
  "gOWXNq4.jpg",
  "gQ5IrM1.png",
  "grnjkmC.mp4",
  "grnjkmC.png",
  "gSIIyeB.png",
  "gU5VXx6.png",
  "gvG7DdM.png",
  "gxQ3QA1.jpg",
  "gXRUp18.png",
  "GYO1iQ2.mp4",
  "HAcOU3v.png",
  "hHsbc7S.png",
  "hJaM5kV.png",
  "HjCvwIN.png",
  "HkRdXLb.jpg",
  "hlW6W6r.png",
  "HmgnFRA.png",
  "HQTcDUW.png",
  "hsf6LRW.png",
  "HSkjbnz.jpg",
  "HToMlpe.jpg",
  "HUn9bPx.png",
  "HZRVd8n.png",
  "HZUfeFE.png",
  "HZUqd1D.png",
  "I0XMeOz.png",
  "i1QUncM.png",
  "i22hSwj.jpg",
  "IdEATD3.png",
  "iE7FGly.jpg",
  "Ih8S99c.png",
  "IjN1dT6.png",
  "iLaweEn.png",
  "iMoj5qA.jpg",
  "IoB18cV.png",
  "ISnaLBD.png",
  "IToOtId.jpg",
  "ivyomjK.png",
  "j57FbGf.jpg",
  "j83kSI7.mp4",
  "j83kSI7.png",
  "jaxstnK.png",
  "JSukWUk.png",
  "jT7bq4S.jpg",
  "JWSIr2c.jpg",
  "jz8J5P8.jpg",
  "K2bqxvt.png",
  "K3pxorP.png",
  "kBcTyaj.jpg",
  "kD1Y1va.png",
  "KDsIbXY.png",
  "KDue2cs.gif",
  "kfim2Sr.png",
  "kfN64ue.png",
  "KkkHdSW.png",
  "KnSlyi7.gif",
  "knt3sVA.png",
  "KOr08u6.jpg",
  "kp3sQae.png",
  "kq1mQMI.jpg",
  "ks1Zyfa.png",
  "ksais63.png",
  "kvh0ild.png",
  "KxmFRfz.jpg",
  "kxsWOKq.png",
  "KyoG8de.png",
  "L1YCyR1.mp4",
  "L1YCyR1.png",
  "Ldq6QRR.jpg",
  "LfGW6sl.jpg",
  "litybtv.png",
  "LJhiN0m.jpg",
  "LLrlxHV.jpg",
  "LP60W0A.jpg",
  "lQHpR5x.jpg",
  "Lrk5Erw.png",
  "lRpdIge.jpg",
  "lRpdIge.mp4",
  "LSarK9j.png",
  "lWi60zs.png",
  "LXLxwnq.jpg",
  "M060Hxu.jpg",
  "M3b6wLw.png",
  "MaE1ICP.png",
  "mBIWm9E.png",
  "mGjKDOT.png",
  "MHJo2My.png",
  "mJ5eAVi.jpg",
  "Mlrx3f6.png",
  "MMBYhc6.png",
  "mOL28YC.gif",
  "mQdOrFt.jpg",
  "MsRNmcq.mp4",
  "MsRNmcq.png",
  "mt3cuML.png",
  "Mtys2r2.png",
  "MVg1gAS.png",
  "mXnSeko.png",
  "Mz4SiA4.png",
  "nbgX3uo.png",
  "Ndzfn2W.jpg",
  "nExINgG.jpg",
  "NHmCcdx.jpg",
  "nOY5hkR.png",
  "nsAjW5T.jpg",
  "nsAjW5T.mp4",
  "NTPLsYf.png",
  "nuRnffr.png",
  "nxdq3c7.png",
  "nZ3mTGC.png",
  "O4MnmPw.png",
  "O4n5yro.png",
  "o86uzUJ.png",
  "oChHkRw.png",
  "OeFzvsb.png",
  "ohDvIaW.png",
  "ojRlkRk.jpg",
  "olWF73B.png",
  "OPSRQJg.png",
  "oRzHNX6.jpg",
  "os6nuxz.png",
  "p1h802V.png",
  "p1UoRS3.mp4",
  "p1UoRS3.png",
  "p7sbXcL.png",
  "p8EKTeo.png",
  "pa3AFfa.png",
  "pBlXfo7.gif",
  "PdFBJC6.png",
  "pdHUeXO.png",
  "PfIYGRN.png",
  "pILtgDp.png",
  "pjWr2gG.png",
  "PlBhEe5.jpg",
  "PPEmzME.png",
  "pxNB1D6.png",
  "qczcNjH.png",
  "QEVkk3s.jpg",
  "Qg0ikxA.jpg",
  "qkRO8b6.jpg",
  "QMUA2AB.png",
  "QmyMrN8.jpg",
  "QpPWrXU.png",
  "QSpwkNV.jpg",
  "QSr7f1s.png",
  "QtWv6Z8.jpg",
  "QtWv6Z8.mp4",
  "r3OPum2.png",
  "rA2hlhR.png",
  "RCJ5i9i.png",
  "rGQkxnr.gif",
  "RHiNHaU.png",
  "RIPHm7J.png",
  "RiqwV1Q.png",
  "rL2Xcm3.png",
  "rmweViq.png",
  "rp8lLwQ.png",
  "Rr3OTDE.png",
  "ruwvVbW.png",
  "RxRM1lW.png",
  "S6khzhg.gif",
  "S6PcMxi.png",
  "s7ZitgL.png",
  "Sa9oicX.png",
  "SecOW6S.png",
  "SjgJWZn.png",
  "SKsNnij.png",
  "sKSUWMC.png",
  "SlgvXuE.png",
  "SLTulBp.jpg",
  "SLTulBp.mp4",
  "sMUO99b.jpg",
  "SNdTxzm.png",
  "SqDk1tO.jpg",
  "Sz3XCdu.jpg",
  "TJ7KhMn.png",
  "TK1Mo66.jpg",
  "Tk4GIeV.png",
  "TMCIxrg.png",
  "tmK3E7x.png",
  "TnjrrRD.png",
  "To5U8Vj.png",
  "TvbU95n.png",
  "tVJy7dV.png",
  "TwSkOY7.png",
  "tyC6fyz.jpg",
  "U0uT02l.mp4",
  "U0uT02l.png",
  "uc9KQOF.png",
  "udk0QyR.jpg",
  "UhEGkzn.jpg",
  "UHvLlvr.jpg",
  "UJ8Mjhl.png",
  "uNrHVci.png",
  "uUwZMGR.png",
  "UVJGjzR.png",
  "UvKEmf7.jpg",
  "UWUwe7m.png",
  "uYUS46G.jpg",
  "uyXCObF.png",
  "v0Knj3W.png",
  "V6sFYjP.png",
  "v9hDvcg.png",
  "V9kHfCS.gif",
  "v9lYGlE.png",
  "vBDcpaL.png",
  "VIlJk3Y.mp4",
  "VIlJk3Y.png",
  "vIPttW6.png",
  "VJu2XCJ.png",
  "VLQ5fCV.gif",
  "Vmn2bnJ.png",
  "vR07MdW.jpg",
  "VSCDGkQ.jpg",
  "VSCDGkQ.mp4",
  "VtUPc6D.png",
  "VUIQWmk.jpg",
  "VVqsDXH.png",
  "vwYbil8.png",
  "VX8u6vM.png",
  "Vy4H3Ms.png",
  "vyClfzz.png",
  "vzG1QZj.png",
  "w4jhZna.png",
  "waybbXq.gif",
  "WD5ZzBg.png",
  "We9Vi6a.png",
  "WlFEqzG.png",
  "Wmrtrow.png",
  "WNybN7b.mp4",
  "WOB1w7S.png",
  "WPtWVOj.png",
  "WqkmrQf.jpg",
  "wUiUkdH.png",
  "WVNHbnu.png",
  "x41cioC.jpg",
  "X9L0XcO.png",
  "XaLZdW2.jpg",
  "xbkqiP4.png",
  "XdFK3uA.jpg",
  "XehK5Z7.png",
  "XFmD7Is.png",
  "XFR7m2E.mp4",
  "XFR7m2E.png",
  "xHmJ8Nq.png",
  "xL4I3hL.png",
  "xMlnCuQ.jpg",
  "XNo0xSk.jpg",
  "XpEm2VJ.png",
  "xqjlPZ3.jpg",
  "XS34sOM.mp4",
  "XS34sOM.png",
  "XSqtDMi.jpg",
  "xSwN6sy.jpg",
  "Xvb7A1T.mp4",
  "Xvb7A1T.png",
  "Y2lxdRA.jpg",
  "yC4nscY.png",
  "YDA6HgR.png",
  "yFnkVKs.png",
  "YfubuM4.png",
  "yiwSsMK.jpg",
  "yjWenJM.png",
  "YnxsDwQ.jpg",
  "yONidkC.png",
  "yOOUeCI.png",
  "YPEkYqr.png",
  "YpfMce3.png",
  "yQlsKK6.png",
  "YRDLKbV.jpg",
  "YtBD7k4.jpg",
  "yZh2fmo.gif",
  "Z06Nhkg.png",
  "Z4mQih3.png",
  "z8zEMZ5.png",
  "zIqzECD.png",
  "ZKyQbHm.png",
  "zLaluPn.png",
  "zLC4R96.png",
  "zMLbszv.png",
  "ZN5ZZFs.png",
  "zpv3plJ.png",
  "zQLNbVo.png",
  "zTKSD90.png",
  "ZVBDy8T.png",
  "ZyC9DNj.png",
];

async function download() {
  for (const imgurId of imgurIds) {
    if (existsSync(`./assets/${imgurId}`)) {
      console.log(`Skipping ${imgurId}`);
      continue;
    }

    await downloadFile(imgurId);
  }
}

async function downloadFile(imgurId: string) {
  const url = `/assets/${imgurId}`;
  console.log(`downloading ${url}`);

  const response = await fetch(url);

  if (response.ok) {
    const blob = await response.blob();

    await writeFile(`./assets/${imgurId}`, blob.stream());

    return true;
  }

  console.error(`${response.status}: ${response.statusText}`);

  return false;
}

async function downloadImage(imgurId: string) {
  const url = `/assets/${imgurId}.png`;
  console.log(`downloading ${url}`);

  const response = await fetch(url);

  if (response.ok) {
    const blob = await response.blob();

    await writeFile(`./assets/${imgurId}.png`, blob.stream());

    return true;
  }

  console.error(`${response.status}: ${response.statusText}`);

  return false;
}

async function downloadVideo(imgurId: string) {
  const url = `/assets/${imgurId}.mp4`;
  console.log(`downloading ${url}`);

  const response = await fetch(url);

  if (response.ok) {
    const blob = await response.blob();

    await writeFile(`./assets/${imgurId}.mp4`, blob.stream());

    return true;
  }

  console.error(`${response.status}: ${response.statusText}`);

  return false;
}

void download();
